# -*- coding: utf-8 -*-
AddAliquot = "Bika LIMS: Add Aliquot"
AddAnalysisRequest = "Bika LIMS: Add Analysis Request"
AddClient = "Bika LIMS: Add Client"
AddContact = "Bika LIMS: Add Contact"
AddDepartment = "Bika LIMS: Add Department"
AddLIMSRoot = "Bika LIMS: Add LIMSRoot"
AddLaboratory = "Bika LIMS: Add Laboratory"
AddSample = "Bika LIMS: Add Sample"
AddSamplePoint = "Bika LIMS: Add Sample Point"
AddSampleType = "Bika LIMS: Add Sample Type"
